apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-08-26T12:26:24Z"
  generation: 1
  labels:
    app: hashgenerator-dep
  name: hashgenerator-dep
  namespace: default
  resourceVersion: "1371"
  uid: 134d5bd7-3dcc-4e0b-a70a-005d414349bb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hashgenerator-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hashgenerator-dep
    spec:
      containers:
      - image: hash_generator:1.1
        imagePullPolicy: IfNotPresent
        name: hash-generator-4pmdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-26T12:26:24Z"
    lastUpdateTime: "2025-08-26T12:26:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-26T12:26:24Z"
    lastUpdateTime: "2025-08-26T12:26:24Z"
    message: ReplicaSet "hashgenerator-dep-7ddc9646f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
